// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqaDxPdR1k3fKvEZIXSyd7px9C_wyvK9I',
    appId: '1:409091263950:android:4c14adbb91a35fdfe3ef9f',
    messagingSenderId: '409091263950',
    projectId: 'fruits-hub-fcc7e',
    storageBucket: 'fruits-hub-fcc7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiw0A3SoB-Jybrte_7cxiVYX8ONSUaXYs',
    appId: '1:409091263950:ios:d2619e8af6eef0c4e3ef9f',
    messagingSenderId: '409091263950',
    projectId: 'fruits-hub-fcc7e',
    storageBucket: 'fruits-hub-fcc7e.firebasestorage.app',
    androidClientId: '409091263950-oakov5gh5huf08fb2dh5u1821bsmet1o.apps.googleusercontent.com',
    iosClientId: '409091263950-mi3piqugn1ukftfrk6tc11qf1e18jg03.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );
}
